sonar.projectKey=SEU_USUARIO_fase-1-spring-explorer
sonar.organization=SEU_USUARIO

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/config/**,**/dto/**,**/entity/**,**/*Application.java
sonar.test.exclusions=**/test/**

sonar.java.source=17
